"""added_lead_type

Revision ID: 14ba29293ee5
Revises: 4be0e0cbbd95
Create Date: 2020-05-12 22:10:25.249492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba29293ee5'
down_revision = '4be0e0cbbd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False, comment='Название статуса'),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True, comment='Краткое описание'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leads', sa.Column('federal_law', sa.VARCHAR(length=50), nullable=True, comment='Федеральный закон'))
    op.add_column('leads', sa.Column('type_id', sa.BigInteger(), nullable=True, comment='Наименование базы'))
    op.create_index(op.f('ix_leads_type_id'), 'leads', ['type_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'lead_types', ['type_id'], ['id'])
    # ### end Alembic commands ###
    fill_static_data()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_type_id'), table_name='leads')
    op.drop_column('leads', 'type_id')
    op.drop_column('leads', 'federal_law')
    op.drop_table('lead_types')
    # ### end Alembic commands ###


def fill_static_data():
    from source.models.lead import LeadType
    lead_type = LeadType.t

    op.bulk_insert(lead_type,
                   [
                       {'name': 'winner', 'description': 'победитель'},
                       {'name': 'regular', 'description': 'постоянный клиент'},
                       {'name': 'participant', 'description': 'участник'},
                       {'name': 'agent', 'description': 'агент'},
                       {'name': 'analytics', 'description': 'аналитика'},
                       ]
                   )
