"""added_fields_to_lead

Revision ID: aaebfc270892
Revises: 3bdbca75882d
Create Date: 2020-05-06 00:43:02.667492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaebfc270892'
down_revision = '3bdbca75882d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('email', sa.VARCHAR(length=200), nullable=True, comment='email'))
    op.add_column('leads', sa.Column('feedback_type', sa.VARCHAR(length=100), nullable=True, comment='email'))
    op.add_column('leads', sa.Column('in_progress', sa.Boolean(), server_default='0', nullable=False, comment='Флаг забаненного пользователя'))
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_in_progress'), 'leads', ['in_progress'], unique=False)
    op.drop_column('leads', 'contacts')
    # ### end Alembic commands ###

    # add new status
    op.execute("""
        INSERT INTO lead_statuses (name, description)
        VALUES ('production', 'Передан на производство')
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Контакты пользователя'))
    op.drop_index(op.f('ix_leads_in_progress'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_column('leads', 'in_progress')
    op.drop_column('leads', 'feedback_type')
    op.drop_column('leads', 'email')
    # ### end Alembic commands ###
    op.execute("""
        DELETE FROM lead_statuses where  id = 5
    """)
